name: prod

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test and build
      run: |
        npm install
      env:
        CI: true


    - name: Bump version and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        npm version patch --no-git-tag-version
        git add package.json package-lock.json
        git commit -m "chore: bump version skip ci"
        git push origin main --force
        git push origin main --force --tags

    - name: Authenticate with npm
      run: |
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      run: |
        export NODE_AUTH_TOKEN=$NPM_TOKEN
        npm publish --access public
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}