name: prod

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    strategy:
      matrix:
        node-version: [19.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test and build
      run: |
        npm install
        npm run build
      env:
        CI: true

    - name: Install s3cmd
      run: sudo apt-get install -y s3cmd
    - name: Install the Scaleway CLI
      uses: scaleway/action-scw@v0
      with:
        version: v2.37.0
    
    - name: Publish dataleon.min.js to Scaleway
      run: |
        scw object config get type=s3cmd > /home/runner/.s3cfg
        s3cmd --no-mime-magic --guess-mime-type --acl-public put ./build/sdk/js/dataleon.min.js s3://$SCW_BUCKET_NAME/sdk/js/$SHA/dataleon.min.js
        s3cmd --no-mime-magic --guess-mime-type --acl-public put ./build/sdk/js/dataleon.min.js s3://$SCW_BUCKET_NAME/sdk/js/latest/dataleon.min.js
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
        SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
        SCW_DEFAULT_REGION: fr-par
        SCW_BUCKET_NAME: yap-assets-customer
        SHA: ${{ github.sha }}

    - name: Bump version and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        npm version patch --no-git-tag-version
        git add package.json package-lock.json
        git commit -m "chore: bump version skip ci"
        git push -u origin main
        git push --tags

    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}